// Define data globally to avoid CORS/Module issues locally
window.GAME_DATA = {
  games: [
    { id: 1, title: "The Legend of Zelda: Breath of the Wild", developer: "Nintendo EPD", publisher: "Nintendo", platforms: ["Switch", "Wii U"], genres: ["Action-adventure"], year: 2017, series: "The Legend of Zelda" },
    { id: 2, title: "Elden Ring", developer: "FromSoftware", publisher: "Bandai Namco", platforms: ["PS4", "PS5", "Xbox One", "Xbox Series X/S", "PC"], genres: ["Action RPG", "Soulslike"], year: 2022, series: "Souls" },
    { id: 3, title: "God of War Ragnarök", developer: "Santa Monica Studio", publisher: "Sony Interactive Entertainment", platforms: ["PS4", "PS5"], genres: ["Action-adventure", "Hack and slash"], year: 2022, series: "God of War" },
    { id: 4, title: "Red Dead Redemption 2", developer: "Rockstar Studios", publisher: "Rockstar Games", platforms: ["PS4", "Xbox One", "PC"], genres: ["Action-adventure", "Western"], year: 2018, series: "Red Dead" },
    { id: 5, title: "The Witcher 3: Wild Hunt", developer: "CD Projekt Red", publisher: "CD Projekt", platforms: ["PS4", "Xbox One", "PC", "Switch", "PS5", "Xbox Series X/S"], genres: ["Action RPG"], year: 2015, series: "The Witcher" },
    { id: 6, title: "Minecraft", developer: "Mojang Studios", publisher: "Mojang Studios", platforms: ["PC", "Mobile", "Xbox", "PlayStation", "Switch", "Wii U", "3DS"], genres: ["Sandbox", "Survival"], year: 2011, series: "Minecraft" },
    { id: 7, title: "Grand Theft Auto V", developer: "Rockstar North", publisher: "Rockstar Games", platforms: ["PS3", "Xbox 360", "PS4", "Xbox One", "PC", "PS5", "Xbox Series X/S"], genres: ["Action-adventure"], year: 2013, series: "Grand Theft Auto" },
    { id: 8, title: "Hades", developer: "Supergiant Games", publisher: "Supergiant Games", platforms: ["PC", "Switch", "PS4", "PS5", "Xbox One", "Xbox Series X/S"], genres: ["Roguelike", "Action RPG"], year: 2020, series: "None" },
    { id: 9, title: "Stardew Valley", developer: "ConcernedApe", publisher: "ConcernedApe", platforms: ["PC", "PS4", "Xbox One", "Switch", "Mobile", "Vita"], genres: ["Simulation", "RPG"], year: 2016, series: "None" },
    { id: 10, title: "Portal 2", developer: "Valve", publisher: "Valve", platforms: ["PC", "PS3", "Xbox 360", "Switch"], genres: ["Puzzle-platformer"], year: 2011, series: "Portal" },
    { id: 11, title: "Overwatch 2", developer: "Blizzard Entertainment", publisher: "Blizzard Entertainment", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch"], genres: ["FPS", "Hero Shooter"], year: 2022, series: "Overwatch" },
    { id: 12, title: "Fortnite", developer: "Epic Games", publisher: "Epic Games", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch", "Mobile"], genres: ["Battle Royale", "Sandbox"], year: 2017, series: "Fortnite" },
    { id: 13, title: "Super Mario Odyssey", developer: "Nintendo EPD", publisher: "Nintendo", platforms: ["Switch"], genres: ["Platformer"], year: 2017, series: "Super Mario" },
    { id: 14, title: "The Last of Us Part II", developer: "Naughty Dog", publisher: "Sony Interactive Entertainment", platforms: ["PS4", "PS5"], genres: ["Action-adventure", "Survival horror"], year: 2020, series: "The Last of Us" },
    { id: 15, title: "Cyberpunk 2077", developer: "CD Projekt Red", publisher: "CD Projekt", platforms: ["PS4", "Xbox One", "PC", "PS5", "Xbox Series X/S"], genres: ["Action RPG", "FPS"], year: 2020, series: "Cyberpunk" },
    { id: 16, title: "Hollow Knight", developer: "Team Cherry", publisher: "Team Cherry", platforms: ["PC", "Switch", "PS4", "Xbox One"], genres: ["Metroidvania"], year: 2017, series: "Hollow Knight" },
    { id: 17, title: "Among Us", developer: "Innersloth", publisher: "Innersloth", platforms: ["PC", "Mobile", "Switch", "PS4", "PS5", "Xbox One", "Xbox Series X/S"], genres: ["Social deduction"], year: 2018, series: "None" },
    { id: 18, title: "Animal Crossing: New Horizons", developer: "Nintendo EPD", publisher: "Nintendo", platforms: ["Switch"], genres: ["Social simulation"], year: 2020, series: "Animal Crossing" },
    { id: 19, title: "Call of Duty: Modern Warfare II", developer: "Infinity Ward", publisher: "Activision", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"], genres: ["FPS"], year: 2022, series: "Call of Duty" },
    { id: 20, title: "Apex Legends", developer: "Respawn Entertainment", publisher: "Electronic Arts", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch", "Mobile"], genres: ["Battle Royale", "FPS"], year: 2019, series: "Titanfall" },
    { id: 21, title: "Baldur's Gate 3", developer: "Larian Studios", publisher: "Larian Studios", platforms: ["PC", "PS5", "Xbox Series X/S"], genres: ["RPG"], year: 2023, series: "Baldur's Gate" },
    { id: 22, title: "Spider-Man 2", developer: "Insomniac Games", publisher: "Sony Interactive Entertainment", platforms: ["PS5"], genres: ["Action-adventure"], year: 2023, series: "Spider-Man" },
    { id: 23, title: "Starfield", developer: "Bethesda Game Studios", publisher: "Bethesda Softworks", platforms: ["Xbox Series X/S", "PC"], genres: ["Action RPG"], year: 2023, series: "None" },
    { id: 24, title: "Resident Evil 4 (Remake)", developer: "Capcom", publisher: "Capcom", platforms: ["PS4", "PS5", "Xbox Series X/S", "PC"], genres: ["Survival horror"], year: 2023, series: "Resident Evil" },
    { id: 25, title: "Final Fantasy XVI", developer: "Square Enix", publisher: "Square Enix", platforms: ["PS5", "PC"], genres: ["Action RPG"], year: 2023, series: "Final Fantasy" },
    { id: 26, title: "Street Fighter 6", developer: "Capcom", publisher: "Capcom", platforms: ["PS4", "PS5", "Xbox Series X/S", "PC"], genres: ["Fighting"], year: 2023, series: "Street Fighter" },
    { id: 27, title: "Diablo IV", developer: "Blizzard Entertainment", publisher: "Blizzard Entertainment", platforms: ["PS4", "PS5", "Xbox One", "Xbox Series X/S", "PC"], genres: ["Action RPG", "Hack and slash"], year: 2023, series: "Diablo" },
    { id: 28, title: "Horizon Forbidden West", developer: "Guerrilla Games", publisher: "Sony Interactive Entertainment", platforms: ["PS4", "PS5", "PC"], genres: ["Action-adventure"], year: 2022, series: "Horizon" },
    { id: 29, title: "Ghost of Tsushima", developer: "Sucker Punch Productions", publisher: "Sony Interactive Entertainment", platforms: ["PS4", "PS5", "PC"], genres: ["Action-adventure"], year: 2020, series: "None" },
    { id: 30, title: "Doom Eternal", developer: "id Software", publisher: "Bethesda Softworks", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch"], genres: ["FPS"], year: 2020, series: "Doom" },
    { id: 31, title: "Half-Life: Alyx", developer: "Valve", publisher: "Valve", platforms: ["PC"], genres: ["VR", "FPS"], year: 2020, series: "Half-Life" },
    { id: 32, title: "Sekiro: Shadows Die Twice", developer: "FromSoftware", publisher: "Activision", platforms: ["PC", "PS4", "Xbox One"], genres: ["Action-adventure", "Soulslike"], year: 2019, series: "None" },
    { id: 33, title: "Control", developer: "Remedy Entertainment", publisher: "505 Games", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch"], genres: ["Action-adventure"], year: 2019, series: "None" },
    { id: 34, title: "Disco Elysium", developer: "ZA/UM", publisher: "ZA/UM", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch"], genres: ["RPG"], year: 2019, series: "None" },
    { id: 35, title: "Outer Wilds", developer: "Mobius Digital", publisher: "Annapurna Interactive", platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch"], genres: ["Action-adventure"], year: 2019, series: "None" },
    { id: 36, title: "Celeste", developer: "Maddy Makes Games", publisher: "Maddy Makes Games", platforms: ["PC", "PS4", "Xbox One", "Switch"], genres: ["Platformer"], year: 2018, series: "None" },
    { id: 37, title: "Return of the Obra Dinn", developer: "Lucas Pope", publisher: "3909", platforms: ["PC", "PS4", "Xbox One", "Switch"], genres: ["Puzzle"], year: 2018, series: "None" },
    { id: 38, title: "Cuphead", developer: "Studio MDHR", publisher: "Studio MDHR", platforms: ["PC", "Xbox One", "Switch", "PS4"], genres: ["Run and gun", "Platformer"], year: 2017, series: "None" },
    { id: 39, title: "NieR: Automata", developer: "PlatinumGames", publisher: "Square Enix", platforms: ["PC", "PS4", "Xbox One", "Switch"], genres: ["Action RPG"], year: 2017, series: "NieR" },
    { id: 40, title: "Persona 5 Royal", developer: "P-Studio", publisher: "Sega", platforms: ["PS3", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "PC", "Switch"], genres: ["JRPG", "Social simulation"], year: 2019, series: "Persona" },
    { id: 41, title: "Mass Effect Legendary Edition", developer: "BioWare", publisher: "Electronic Arts", platforms: ["PC", "PS4", "Xbox One"], genres: ["Action RPG"], year: 2021, series: "Mass Effect" },
    { id: 42, title: "Fallout 4", developer: "Bethesda Game Studios", publisher: "Bethesda Softworks", platforms: ["PC", "PS4", "Xbox One"], genres: ["Action RPG"], year: 2015, series: "Fallout" },
    { id: 43, title: "Skyrim", developer: "Bethesda Game Studios", publisher: "Bethesda Softworks", platforms: ["PC", "PS3", "Xbox 360", "PS4", "Xbox One", "Switch", "PS5", "Xbox Series X/S"], genres: ["Action RPG"], year: 2011, series: "The Elder Scrolls" },
    { id: 44, title: "BioShock Infinite", developer: "Irrational Games", publisher: "2K Games", platforms: ["PC", "PS3", "Xbox 360"], genres: ["FPS"], year: 2013, series: "BioShock" },
    { id: 45, title: "Dark Souls III", developer: "FromSoftware", publisher: "Bandai Namco", platforms: ["PC", "PS4", "Xbox One"], genres: ["Action RPG", "Soulslike"], year: 2016, series: "Souls" },
    { id: 46, title: "Bloodborne", developer: "FromSoftware", publisher: "Sony Interactive Entertainment", platforms: ["PS4"], genres: ["Action RPG", "Soulslike"], year: 2015, series: "Souls" },
    { id: 47, title: "Uncharted 4: A Thief's End", developer: "Naughty Dog", publisher: "Sony Interactive Entertainment", platforms: ["PS4", "PS5", "PC"], genres: ["Action-adventure"], year: 2016, series: "Uncharted" },
    { id: 48, title: "Rocket League", developer: "Psyonix", publisher: "Psyonix", platforms: ["PC", "PS4", "Xbox One", "Switch"], genres: ["Sports", "Racing"], year: 2015, series: "None" },
    { id: 49, title: "League of Legends", developer: "Riot Games", publisher: "Riot Games", platforms: ["PC"], genres: ["MOBA"], year: 2009, series: "League of Legends" },
    { id: 50, title: "Valorant", developer: "Riot Games", publisher: "Riot Games", platforms: ["PC"], genres: ["FPS"], year: 2020, series: "None" }
  ],
  categories: {
    developers: ["Nintendo EPD", "FromSoftware", "Santa Monica Studio", "Rockstar Studios", "CD Projekt Red", "Mojang Studios", "Valve", "Blizzard Entertainment", "Epic Games", "Naughty Dog", "Team Cherry", "Innersloth", "Infinity Ward", "Respawn Entertainment", "Larian Studios", "Insomniac Games", "Bethesda Game Studios", "Capcom", "Square Enix", "Guerrilla Games", "Sucker Punch Productions", "id Software", "Remedy Entertainment", "BioWare", "Riot Games"],
    publishers: ["Nintendo", "Bandai Namco", "Sony Interactive Entertainment", "Rockstar Games", "CD Projekt", "Valve", "Blizzard Entertainment", "Epic Games", "Activision", "Electronic Arts", "Bethesda Softworks", "Capcom", "Square Enix", "Sega", "2K Games", "Riot Games"],
    platforms: ["Switch", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "PC", "Mobile"],
    genres: ["Action-adventure", "Action RPG", "FPS", "Platformer", "RPG", "Simulation", "Strategy", "Sports", "Racing", "Fighting", "Puzzle", "Horror", "Soulslike", "JRPG", "MOBA"],
    years: ["2010-2014", "2015-2019", "2020-Present", "Before 2010"],
    series: ["The Legend of Zelda", "Souls", "God of War", "Red Dead", "The Witcher", "Minecraft", "Grand Theft Auto", "Portal", "Overwatch", "Fortnite", "Super Mario", "The Last of Us", "Cyberpunk", "Hollow Knight", "Call of Duty", "Resident Evil", "Final Fantasy", "The Elder Scrolls", "Fallout", "Uncharted"]
  }
};
